name-template: 'v$NEXT_PATCH_VERSION 🌈'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🛠 Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label:
      - 'documentation'
      - 'security'
      - 'devops'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR '
template: |
  ## Changes

  $CHANGES
